use_frameworks!

platform :ios, '15.0'

target 'OlympusSDK_Example' do
  use_frameworks!
  
  pod 'OlympusSDK', :path => '../'
  pod 'Charts'
  
  target 'OlympusSDK_Tests' do
    inherit! :search_paths

    
  end
end
