use_frameworks!

platform :ios, '15.0'

target 'OlympusSDK_Example' do
  use_frameworks!
  
  pod 'OlympusSDK', :path => '../'
  pod 'Charts'
  pod 'SnapKit' 
  pod 'Then' 
  pod 'RxSwift', '~> 6.5.0'
  pod 'RxCocoa', '~> 6.5.0'
  pod 'lottie-ios' 
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

  target 'OlympusSDK_Tests' do
    inherit! :search_paths

    
  end
end
